# Page settings

baseurl = "https://hnandarusdy.github.io/herman-cv/"
languageCode = "en-us"
title = "Herman resume"
theme = "herman-cv"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Herman Nanda Rusdy"
        tagline = "Business/System Analyst"
        avatar = "a.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: hnandarusdy@gmail.com"
        title = "hnandarusdy@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+61424972388"
        title = "+61424972388"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://hnandarusdy.github.io/herman-cv/"
        title = "My Resume"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/hnandarusdy/"
        title = "linkedin.com/in/hnandarusdy/"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/hnandarusdy/"
        title = "github.com/hnandarusdy/"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Master of Information Technology"
        college = "Swinburne University of Melbourne"
        dates = "2013 - 2015"

        [[params.education.list]]
        degree = "Bachelor Degree of Computer Science"
        college = "Bina Nusantara University of Jakarta"
        dates = "2006 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Bahasa Indonesia"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Futsal/Soccer"

        [[params.interests.list]]
        interest = "Reading"

        [[params.interests.list]]
        interest = "Data Analysis"

        [[params.interests.list]]
        interest = "Family Time"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """Beginning my IT journey in 2007 when was hired as lab assisstant to teach other students programming skills,
                  such as VB, PHP, Javascript, C, C++. Promoted as a subject coordinator a year later to coordinate specific subjects,
                  and eventually as a network administrator who is responsible for laboratory installation, configuration and network.
                  </br>
                  </br>
                  I moved to Australia in 2013 to pursue my career as a BA and I have been working in this position since 2015. My
                  biggest interests are about solving problems and data analytics. I am really interested in studying Machine Learning
                  for my next step career.
                  """
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Business / System Analyst"
        dates = "2015 - Present"
        company = "Clearbridge Group PTY LTD, Melbourne, Australia"
        details = """<li>Gathering requirements from stakeholders and turn into use case/user stories/RTM and test cases</li>
                  <li>Create and manage reporting dashboard from CRM and Accounting (saasu) system with bigquery and Google Data Studio</li>
                  <li>Data wrangling with Pentaho and Trifacta</li>
                  <li>Working closely with PM to manage projects with Agile Development</li>
                  <li>Interviewing and solving client's problems</li>
                  <li>Responsible for users' training for new features</li>
                  <li>Managing deployment of kubernetes/Docker environment</li>
                  """

        [[params.jobs.list]]
        position = "Internship Business Analyst/QA "
        dates = "March 2015 - May 2015"
        company = "Media Link Australia"
        details = """<li>Create user stories based on user specific requirements, create test cases, and test the functionality and the GUI.</li>
                  <li>Working closely with Project Manager to manage projects</li>
                  <li>Tracking projects from JIRA</li>
                  """

        [[params.jobs.list]]
        position = "Tutor"
        dates = "Feb 2015 - Oct 2015"
        company = "Junior Engineer"
        details = "Teaching primary school students about basic programming "

        [[params.jobs.list]]
        position = "Unit Manager"
        dates = "2011 - 2013"
        company = "Prudential"
        details = "Manage teams to reach target every month"

        [[params.jobs.list]]
        position = "Subject Coordinator and Network Administrator"
        dates = "2007-2010"
        company = "Software Laboratory Center, Bina Nusantara University"
        details = """<li>Designing, maintaining, and troubleshooting network and system operational in Software Laboratory that involves Novell Netware and Windows Platform</li>
                  <li>Designing, maintaining, and troubleshooting network and system security on Novell Netware and Windows platform for around 1500 workstations and users that includes student, software laboratory staffs, and teaching assistants, with different needs and security access</li>
                  <li>Providing technical support in network, system and infrastructure for activities that were held in or by Software Laboratory</li>
                  <li>Responsible for quality of laboratory material including exam material and examination criteria</li>
                  <li>Installation and maintenance of servers and workstations. Hardware upgrades for servers and workstations.</li>
                  <li>Teaching and assisting university students in lab sessions of various programming language and software usage</li>
                  """

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**These are the projects that I have worked on. From being developers and BA"

        [[params.projects.list]]
        title = "CBBA"
        #url = "https://github.com/aerohub/hugrid"
        tagline = "**Workflow**. This project is based on BPMN2, built by jBPM with REST API to MeteorJS + ReactJS and mongoDB as the database collection. With a support of Docker, ElasticSearch and lastly, pentaho for data wrangling to ETL database"

        [[params.projects.list]]
        title = "CBBA Courier Dashboard"
        #url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple application that read from the main database to display data from production(order) to customer(delivery). This is integrated with UPS and Machship[Freigh Concept]"

        [[params.projects.list]]
        title = "Form Builder"
        #url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "This is built using Mozilla Formbuilder with ElectrodeJS. The purpose of this application is to support human tasks that are generated from jBPM. It can create forms with ease."

        [[params.projects.list]]
        title = "Shipping Calculator"
        #url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "A simple application that integrates with Machship and PandaDoc (Quotation System) to calculate shipping costs from various couriers in Australia"

        [[params.projects.list]]
        title = "Close IO Data Dashboard"
        #url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "KPI reporting dashboard for sales team that allows decision-makers to take actions. This reporting is using Google BigQuery, Google Data Studio, kubernetes, Python"

        [[params.projects.list]]
        title = "Saasu Data Dashboard"
        #url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "Live streaming financial data dashboard report for management team.  This reporting is using Google BigQuery, Google Data Studio, kubernetes, Python"

        [[params.projects.list]]
        title = "Retail Management"
        #url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "Build with VBA and MsAccess for a simple application that controls stock system"

        [[params.projects.list]]
        title = "Timesheet Management System"
        #url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "Build with ASP.NET and SQL Server in order to solve timesheet problem"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"


        [[params.skills.list]]
        skill = "AGILE Development Methodology"
        level = "95%"

        [[params.skills.list]]
        skill = "BA Skills (BPMN, DFD, RTM, Use Case, User Stories)"
        level = "95%"

        [[params.skills.list]]
        skill = "Pentaho + Trifacta (Data Wrangling Tools)"
        level = "95%"

        [[params.skills.list]]
        skill = "Data Visualisation(Google Data Studio and Tableau)"
        level = "95%"

        [[params.skills.list]]
        skill = "Database Skills (SQL and nonSQL queries) - MySQL, postGreSQL, SQL Server, MongoDB, Bigquery"
        level = "95%"

        [[params.skills.list]]
        skill = "Versioning Control (Git and Bitbucket)"
        level = "90%"

        [[params.skills.list]]
        skill = "Project Management (PMBOK) using Jira and Confluence"
        level = "85%"

        [[params.skills.list]]
        skill = "OS (Microsoft & Linux) including Linux scripting"
        level = "80%"

        [[params.skills.list]]
        skill = "Google Cloud Platform and Clusters (VM, Kubernetes, Docker)"
        level = "65%"

        [[params.skills.list]]
        skill = "Google Admin Console "
        level = "65%"

        [[params.skills.list]]
        skill = "Web Development(PHP,reactJS,NodeJS,HTML)"
        level = "55%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.
    [params.portfolios]
        enable = true
        icon = "fa fa-camera-retro fa-4x"

        [[params.portfolios.list]]
        name = "SAASU"
        url = "https://datastudio.google.com/u/0/reporting/1q7HhtHtWRu5R-LR9Mw2ROT04OHYY3ge1/page/KPoN"
        image_src = "saasu.jpg"

        [[params.portfolios.list]]
        name = "CLOSEIO"
        image_src = "closeio.jpg"

        [[params.portfolios.list]]
        name = "CBBA"
        image_src = "cbba.jpg"

    [params.footer]
        copyright = "Herman Nanda Rusdy"
